export const GET_USER_API  = 'GET_USER_API'

export const API_USER_DELETE  = 'API_USER_DELETE'
export const IS_API_USER_UPDATED = 'IS_API_USER_UPDATED'
export const USER_API_DATA_ADD = 'USER_API_DATA_ADD'
export const SET_EDIT_USER_MODAL_DATA = 'SET_EDIT_USER_MODAL_DATA'
export const IS_MODAL_OPEN = 'IS_MODAL_OPEN'
export const IS_MODAL_CLOSE = 'IS_MODAL_CLOSE'